package com.brocade.dcm.domain.model;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dept.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dept.dname
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dept.loc
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dept.deptno
     *
     * @return the value of public.dept.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dept.deptno
     *
     * @param deptno the value for public.dept.deptno
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dept.dname
     *
     * @return the value of public.dept.dname
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dept.dname
     *
     * @param dname the value for public.dept.dname
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dept.loc
     *
     * @return the value of public.dept.loc
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dept.loc
     *
     * @param loc the value for public.dept.loc
     *
     * @mbg.generated Tue May 23 21:55:33 PDT 2017
     */
    public void setLoc(String loc) {
        this.loc = loc;
    }
}